"use client";

import React, { useMemo } from 'react';
import { getLayoutByLayoutId } from '../../presentation-templates';

interface PresentationLayoutRendererProps {
  slide: any;
  theme?: any;
}

/**
 * Smart renderer that bridges the gap between generic slide data 
 * and professional layout-specific schemas.
 */
export const PresentationLayoutRenderer: React.FC<PresentationLayoutRendererProps> = ({ slide, theme }) => {
  // 1. Find the professional layout component with fallback logic
  const layoutEntry = useMemo(() => {
    let layoutId = slide.layout;
    
    if (!layoutId) {
      // Map slide.type to a premium layout ID from general/neo-general templates
      const type = slide.type?.toLowerCase() || "";
      switch (type) {
        case 'title':
        case 'hero':
        case 'cover':
          layoutId = 'general:general-intro-slide';
          break;
        case 'bullets':
        case 'bullet_list':
          layoutId = 'general:bullet-with-icons-slide';
          break;
        case 'stats':
        case 'metrics':
        case 'data_grid':
          layoutId = 'general:metrics-slide';
          break;
        case 'quote':
          layoutId = 'general:quote-slide';
          break;
        case 'timeline':
          layoutId = 'neo-general:timeline-alternating-cards-slide';
          break;
        case 'closing':
        case 'conclusion':
          layoutId = 'general:basic-info-slide';
          break;
        case 'code':
        case 'code_showcase':
          layoutId = 'code:description-text';
          break;
        default:
          layoutId = 'general:basic-info-slide';
          break;
      }
    }
    
    console.log(`[PresentationLayoutRenderer] Mapping layout for slide type "${slide.type}": ${layoutId}`);
    return getLayoutByLayoutId(layoutId);
  }, [slide.layout, slide.type]);

  // 2. Map generic slide content to template-specific data
  const templateData = useMemo(() => {
    const { content, images, icons } = slide;
    
    // Start with ALL content properties generated by the LLM natively
    // We combine the slide root properties (since backend returns them at the root) and slide.content
    const data: any = { 
      ...(typeof content === 'object' ? content : {}),
      ...(slide || {})
    };
    
    // Ensure fallbacks for common fields if not natively present
    if (!data.title) data.title = slide.title || content?.title || "";
    if (!data.description) {
      data.description = slide.content || content?.description || (typeof content?.body === 'string' ? content.body : "");
    }
    if (!data.mainDescription) data.mainDescription = data.description;
    if (!data.heading) data.heading = data.title;

    // Premium image selection with realistic fallbacks
    const premiumImages = [
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1000&q=80', // High-tech space / dark theme
      'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1000&q=80', // Meeting room / team
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80', // Tech analytics charts
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1000&q=80', // Cyberpunk network
    ];
    
    // Pick an image based on the slide index to keep them diverse
    const defaultImage = premiumImages[(slide.index || 0) % premiumImages.length];

    if (!data.image) {
      const imgUrl = (images && images.length > 0) ? images[0] : defaultImage;
      data.image = {
        __image_url__: imgUrl,
        __image_prompt__: slide.content?.image_prompts?.[0] || data.title || "strategic overview image"
      };
    }
    
    if (!data.backgroundImage) {
      data.backgroundImage = data.image;
    }

    // Handle bulletPoints for general:bullet-with-icons-slide
    const rawBullets = slide.bullets || content?.bullets || [];
    if (Array.isArray(rawBullets) && rawBullets.length > 0) {
      data.bulletPoints = rawBullets.map((bullet: any, idx: number) => {
        if (typeof bullet === 'string') {
          // Parse string into title and description if it has a separator
          let bTitle = bullet;
          let bDesc = "";
          const splitters = [": ", " - ", " – "];
          for (const splitter of splitters) {
            if (bullet.includes(splitter)) {
              const parts = bullet.split(splitter);
              bTitle = parts[0].trim();
              bDesc = parts.slice(1).join(splitter).trim();
              break;
            }
          }
          if (!bDesc) {
            bDesc = bullet;
          }
          return {
            title: bTitle.slice(0, 100),
            description: bDesc.slice(0, 150),
            icon: {
              __icon_url__: icons?.[idx] || 'https://presenton-public.s3.ap-southeast-1.amazonaws.com/static/icons/bold/checks-bold.svg',
              __icon_query__: 'check'
            }
          };
        } else if (typeof bullet === 'object' && bullet !== null) {
          return {
            title: (bullet.title || bullet.heading || "Point " + (idx + 1)).slice(0, 100),
            description: (bullet.description || bullet.text || "").slice(0, 150),
            icon: {
              __icon_url__: bullet.icon?.__icon_url__ || icons?.[idx] || 'https://presenton-public.s3.ap-southeast-1.amazonaws.com/static/icons/bold/checks-bold.svg',
              __icon_query__: bullet.icon?.__icon_query__ || 'check'
            }
          };
        }
        return null;
      }).filter(Boolean);
    }

    // Handle metrics/stats for general:metrics-slide
    const rawStats = slide.stats || content?.stats || [];
    if (Array.isArray(rawStats) && rawStats.length > 0) {
      data.metrics = rawStats.map((stat: any, idx: number) => {
        const val = stat.value || "100%";
        const lbl = stat.label || "Индикатор";
        let finalLabel = lbl;
        let finalDesc = "";
        
        // If label is too long, it fits better in description
        if (lbl.length > 25) {
          finalLabel = "Показатель " + (idx + 1);
          finalDesc = lbl;
        } else {
          finalDesc = data.description || "Ключевой показатель эффективности проекта";
        }
        return {
          value: val,
          label: finalLabel,
          description: finalDesc
        };
      });
    }

    // Handle quote slide specific mappings
    if (slide.type === 'quote') {
      data.quote = data.description || "Инновации определяют наше общее будущее.";
      data.author = (rawBullets && rawBullets.length > 0 && typeof rawBullets[0] === 'string') 
        ? rawBullets[0] 
        : "COSMO Analytical Engine";
    }

    // Handle title / cover slide specific mappings
    if (slide.type === 'title') {
      data.presenterName = "COSMO Deep Research";
      data.presentationDate = "Май 2026";
    }

    // Handle sections structure for list templates
    if (Array.isArray(content?.body) && !data.sections) {
      data.sections = content.body.map((item: any, idx: number) => ({
        title: item.heading || item.title || `Элемент ${idx + 1}`,
        description: item.description || "",
        icon: icons?.[idx] ? {
            __icon_url__: icons[idx],
            __icon_query__: "icon" 
        } : undefined
      }));
    }

    // Pass through company/logo metadata
    data.__companyName__ = slide.properties?.companyName || "COSMO Artist";
    data._logo_url__ = slide.properties?.logoUrl || "https://presenton-public.s3.ap-southeast-1.amazonaws.com/static/icons/bold/fediverse-logo-bold.svg";

    return data;
  }, [slide]);

  // 3. Fallback warning and basic render if layout not found
  if (!layoutEntry) {
    console.warn(`[PresentationLayoutRenderer] Layout entry not resolved for layout: ${slide.layout}. Falling back.`);
    return (
      <div className="w-full h-full bg-white p-10 flex flex-col items-center justify-center border-4 border-dashed border-red-200">
        <h1 className="text-2xl font-bold text-red-500 mb-4">Layout Missing: {slide.layout || slide.type}</h1>
        <div className="text-gray-800 max-w-2xl">
          <h2 className="text-xl font-bold">{templateData.title}</h2>
          <p>{templateData.description}</p>
        </div>
      </div>
    );
  }

  const LayoutComponent = layoutEntry.component;

  return (
    <div className="w-full h-full presentation-layout-container" data-debug={JSON.stringify(templateData)}>
      <LayoutComponent data={templateData} />
    </div>
  );
};
