version: "3.9"
services:
  nango:
    image: nangohq/nango-server:hosted-0.69.50
    ports:
      - "3003:3003"
    environment:
      - NANGO_DB_MIGRATION_FOLDER=/usr/nango/packages/database/lib/migrations
      - RECORDS_DATABASE_URL=postgresql://nango:nango@nango-db:5432/nango
      - DATABASE_URL=postgresql://nango:nango@nango-db:5432/nango
      - NANGO_DB_HOST=nango-db
      - NANGO_DB_USER=nango
      - NANGO_DB_PASSWORD=nango
      - SERVER_PORT=3003
      - SECRET_KEY=${NANGO_SECRET_KEY:-supersecretkey32chars_changeme!}
      - FLAG_AUTH_ENABLED=false
      - NANGO_SERVER_URL=http://localhost:3003
      - NANGO_DASHBOARD_USERNAME=admin
      - NANGO_REDIS_HOST=nango-redis
      - NANGO_REDIS_URL=redis://nango-redis:6379
      - NANGO_DASHBOARD_PASSWORD=archimedes2026
      - NANGO_ENCRYPTION_KEY=3Y/fJD5G6xiL3pexlqGhLmYbLRFBUp4yJLq2j4wWXz0=
    depends_on:
      - nango-db

  nango-db:
    image: postgres:15
    environment:
      POSTGRES_DB: nango
      POSTGRES_USER: nango
      POSTGRES_PASSWORD: nango
    volumes:
      - nango_data2:/var/lib/postgresql/data

  nango-redis:
    image: redis:7.2.4
    container_name: nango-redis
    ports:
      - "6379:6379"

volumes:
  nango_data2:
