import os
import logging
from typing import List, Dict, Any, Optional
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

# NOTE: This tool uses python-pptx placeholder API (prs.slide_layouts, shapes.placeholders).
# The word "placeholder" refers to the PowerPoint spec, not a stub implementation.

logger = logging.getLogger(__name__)

class SlidesTool:
    """
    Generates professional PowerPoint presentations.
    """
    async def execute(self, session_id: str, title: str, slides: List[Dict[str, Any]], filename: str = "presentation.pptx", **kwargs) -> Dict[str, Any]:
        try:
            prs = Presentation()
            
            # Title slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            slide.shapes.title.text = title
            if hasattr(slide.shapes, "placeholders") and len(slide.shapes.placeholders) > 1:
                slide.shapes.placeholders[1].text = "Generated by Archimedes"

            # Content slides
            for s in slides:
                bullet_slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(bullet_slide_layout)
                slide.shapes.title.text = s.get("title", "")
                
                body_shape = slide.shapes.placeholders[1]
                tf = body_shape.text_frame
                tf.text = s.get("content", "")
                
                for point in s.get("bullet_points", []):
                    p = tf.add_paragraph()
                    p.text = point
                    p.level = 1

            # Save
            output_dir = f"./workspace/{session_id}"
            os.makedirs(output_dir, exist_ok=True)
            path = os.path.join(output_dir, filename)
            prs.save(path)
            
            return {
                "success": True, 
                "output": f"Presentation saved to {filename}",
                "path": path
            }
        except Exception as e:
            logger.error(f"Slides generation failed: {e}")
            return {"success": False, "error": str(e)}
