from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import io

THEMES = {
    "dark": {
        "bg": RGBColor(0x0F, 0x11, 0x17),      # #0F1117
        "accent": RGBColor(0x6C, 0x63, 0xFF),   # #6C63FF
        "title_color": RGBColor(0xFF, 0xFF, 0xFF),
        "body_color": RGBColor(0xE2, 0xE8, 0xF0),
        "card_bg": RGBColor(0x1E, 0x20, 0x2E),
    },
    "light": {
        "bg": RGBColor(0xF8, 0xF9, 0xFA),
        "accent": RGBColor(0x6C, 0x63, 0xFF),
        "title_color": RGBColor(0x11, 0x11, 0x11),
        "body_color": RGBColor(0x44, 0x44, 0x44),
        "card_bg": RGBColor(0xFF, 0xFF, 0xFF),
    },
    "navy": {
        "bg": RGBColor(0x1A, 0x1A, 0x2E),
        "accent": RGBColor(0x00, 0xD2, 0xFF),
        "title_color": RGBColor(0xFF, 0xFF, 0xFF),
        "body_color": RGBColor(0xB0, 0xBE, 0xC5),
        "card_bg": RGBColor(0x16, 0x21, 0x3E),
    }
}

def _apply_slide_background(slide, prs, color: RGBColor):
    """Заливает фон слайда цветом."""
    from pptx.oxml.ns import qn
    from lxml import etree
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = color

def _add_text_box(slide, text, left, top, width, height, 
                  font_size, bold, color, align=PP_ALIGN.LEFT):
    from pptx.util import Inches, Pt
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = color

class SlidesTool:
    def get_definition(self):
        return {
            "type": "function",
            "function": {
                "name": "slides",
                "description": "Create professional PowerPoint presentations.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "filename": {"type": "string", "default": "presentation.pptx"},
                        "theme": {"type": "string", "enum": ["dark", "light", "navy"], "default": "dark"},
                        "slides": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "title": {"type": "string"},
                                    "content": {"type": "string"},
                                    "bullet_points": {
                                        "type": "array",
                                        "items": {"type": "string"}
                                    }
                                },
                                "required": ["title"]
                            }
                        }
                    },
                    "required": ["title", "slides"]
                }
            }
        }

    async def execute(self, session_id: str, title: str, 
                      slides: list, filename: str = "presentation.pptx",
                      theme: str = "dark", **kwargs):
        try:
            t = THEMES.get(theme, THEMES["dark"])
            prs = Presentation()
            prs.slide_width = Inches(13.33)
            prs.slide_height = Inches(7.5)
            
            blank_layout = prs.slide_layouts[6]  # полностью пустой
            
            # === TITLE SLIDE ===
            slide = prs.slides.add_slide(blank_layout)
            _apply_slide_background(slide, prs, t["bg"])
            
            # Акцентная полоса
            from pptx.util import Inches, Pt
            line = slide.shapes.add_shape(
                1,  # MSO_SHAPE_TYPE.RECTANGLE
                Inches(0), Inches(3.4), Inches(13.33), Inches(0.06)
            )
            line.fill.solid()
            line.fill.fore_color.rgb = t["accent"]
            line.line.fill.background()
            
            # Заголовок
            _add_text_box(slide, title,
                left=Inches(1), top=Inches(2.2),
                width=Inches(11), height=Inches(1.2),
                font_size=44, bold=True,
                color=t["title_color"], align=PP_ALIGN.LEFT)
            
            # Подзаголовок
            _add_text_box(slide, "Generated by Archimedes",
                left=Inches(1), top=Inches(3.6),
                width=Inches(8), height=Inches(0.5),
                font_size=16, bold=False,
                color=t["accent"], align=PP_ALIGN.LEFT)
            
            # === CONTENT SLIDES ===
            for s in slides:
                slide = prs.slides.add_slide(blank_layout)
                _apply_slide_background(slide, prs, t["bg"])
                
                # Заголовок слайда
                _add_text_box(slide, s.get("title", ""),
                    left=Inches(0.8), top=Inches(0.4),
                    width=Inches(11.7), height=Inches(0.8),
                    font_size=32, bold=True,
                    color=t["title_color"])
                
                # Акцентная линия под заголовком
                line = slide.shapes.add_shape(1,
                    Inches(0.8), Inches(1.3), Inches(2), Inches(0.04))
                line.fill.solid()
                line.fill.fore_color.rgb = t["accent"]
                line.line.fill.background()
                
                # Контент
                content = s.get("content", "")
                points = s.get("bullet_points", [])
                
                if content:
                    _add_text_box(slide, content,
                        left=Inches(0.8), top=Inches(1.6),
                        width=Inches(11.7), height=Inches(1.2),
                        font_size=18, bold=False,
                        color=t["body_color"])
                
                # Буллеты как карточки
                for i, point in enumerate(points[:6]):
                    card = slide.shapes.add_shape(1,
                        Inches(0.8), Inches(2.2 + i * 0.75),
                        Inches(11.7), Inches(0.65))
                    card.fill.solid()
                    card.fill.fore_color.rgb = t["card_bg"]
                    card.line.color.rgb = t["accent"]
                    card.line.width = Pt(0.5)
                    
                    _add_text_box(slide, f"  {point}",
                        left=Inches(0.8), top=Inches(2.22 + i * 0.75),
                        width=Inches(11.7), height=Inches(0.65),
                        font_size=15, bold=False,
                        color=t["body_color"])
            
            # Сохранить в байты → отправить в контейнер
            buf = io.BytesIO()
            prs.save(buf)
            buf.seek(0)
            import base64
            b64 = base64.b64encode(buf.read()).decode()
            
            from backend.sandbox.singleton import sandbox_manager
            remote_path = f"/home/ubuntu/workspace/{filename}"
            cmd = f"echo '{b64}' | base64 -d > {remote_path}"
            result = await sandbox_manager.executor.run_command(session_id, cmd)
            
            return {
                "success": True,
                "output": f"Presentation '{filename}' created ({len(slides)+1} slides, theme: {theme})",
                "path": remote_path
            }
        except Exception as e:
            return {"success": False, "error": str(e)}
