"""Initial migration

Revision ID: f93aa791ea4f
Revises: 
Create Date: 2026-05-01 00:58:33.241658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f93aa791ea4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyvaluesqlmodel_key'), table_name='keyvaluesqlmodel')
    op.drop_table('keyvaluesqlmodel')
    op.drop_index(op.f('ix_slides_presentation'), table_name='slides')
    op.drop_table('slides')
    op.drop_index(op.f('ix_presentation_layout_codes_presentation'), table_name='presentation_layout_codes')
    op.drop_table('presentation_layout_codes')
    op.drop_table('presentations')
    op.drop_table('templates')
    op.drop_table('async_presentation_generation_tasks')
    op.drop_index(op.f('ix_webhook_subscriptions_event'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_table('imageasset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageasset',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extras', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('imageasset_pkey'))
    )
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_webhook_subscriptions_event'), 'webhook_subscriptions', ['event'], unique=False)
    op.create_table('async_presentation_generation_tasks',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('async_presentation_generation_tasks_pkey'))
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('templates_pkey'))
    )
    op.create_table('presentations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('n_slides', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_paths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outlines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('layout', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('structure', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('theme', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verbosity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('include_table_of_contents', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_title_slide', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('web_search', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('presentations_pkey'))
    )
    op.create_table('presentation_layout_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('presentation', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('layout_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('layout_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('layout_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fonts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('presentation_layout_codes_pkey'))
    )
    op.create_index(op.f('ix_presentation_layout_codes_presentation'), 'presentation_layout_codes', ['presentation'], unique=False)
    op.create_table('slides',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('presentation', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('layout_group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('layout', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('html_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('speaker_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['presentation'], ['presentations.id'], name=op.f('slides_presentation_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('slides_pkey'))
    )
    op.create_index(op.f('ix_slides_presentation'), 'slides', ['presentation'], unique=False)
    op.create_table('keyvaluesqlmodel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('keyvaluesqlmodel_pkey'))
    )
    op.create_index(op.f('ix_keyvaluesqlmodel_key'), 'keyvaluesqlmodel', ['key'], unique=False)
    # ### end Alembic commands ###
