import os
import ast
import re
from pathlib import Path

class ProjectMapper:
    def __init__(self, root_dir):
        self.root_dir = Path(root_dir)
        self.ignore_dirs = {
            '.git', '.agents', '.github', '.pytest_cache', 'node_modules', 
            'venv', '__pycache__', 'chroma', 'chroma_db', 'logs', 'dist', 'build'
        }
        self.ignore_files = {'.gitignore', '.env', 'requirements.txt', 'pyproject.toml'}
        self.map_file = self.root_dir / "PROJECT_MAP.md"

    def is_ignored(self, path):
        for part in path.parts:
            if part in self.ignore_dirs:
                return True
        return path.name in self.ignore_files

    def analyze_python(self, file_path):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                tree = ast.parse(f.read())
            
            summary = {"classes": [], "functions": []}
            for node in tree.body:
                if isinstance(node, ast.ClassDef):
                    methods = [n.name for n in node.body if isinstance(n, ast.FunctionDef)]
                    summary["classes"].append({"name": node.name, "methods": methods})
                elif isinstance(node, ast.FunctionDef):
                    summary["functions"].append(node.name)
            return summary
        except Exception as e:
            return f"Error: {str(e)}"

    def analyze_ts(self, file_path):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Simple regex for TS/TSX
            interfaces = re.findall(r'interface\s+(\w+)', content)
            types = re.findall(r'type\s+(\w+)', content)
            functions = re.findall(r'(?:function|const)\s+(\w+)\s*[:=]\s*(?:\([^)]*\)|async)', content)
            components = re.findall(r'const\s+(\w+)\s*:\s*React\.(?:FC|FunctionComponent)', content)
            
            return {
                "interfaces": interfaces,
                "types": types,
                "functions": list(set(functions)),
                "components": components
            }
        except Exception as e:
            return f"Error: {str(e)}"

    def generate(self):
        output = ["# 🗺️ Project Architecture Map: Cosmo / Archimedes\n"]
        output.append("> This file is automatically generated to provide context for AI agents.\n")
        
        sections = {}

        for file_path in self.root_dir.rglob('*'):
            if file_path.is_file() and not self.is_ignored(file_path):
                rel_path = file_path.relative_to(self.root_dir)
                ext = file_path.suffix
                
                # Group by top-level directory
                parts = rel_path.parts
                top_dir = parts[0] if len(parts) > 1 else "Root"
                
                if top_dir not in sections:
                    sections[top_dir] = []
                
                info = {"path": str(rel_path), "ext": ext}
                
                if ext == '.py':
                    info["analysis"] = self.analyze_python(file_path)
                elif ext in ['.ts', '.tsx']:
                    info["analysis"] = self.analyze_ts(file_path)
                
                sections[top_dir].append(info)

        for section, files in sorted(sections.items()):
            output.append(f"## 📁 {section}")
            for f in files:
                output.append(f"### 📄 `{f['path']}`")
                analysis = f.get("analysis")
                if isinstance(analysis, dict):
                    if "classes" in analysis and analysis["classes"]:
                        output.append("**Classes:**")
                        for c in analysis["classes"]:
                            output.append(f"- `{c['name']}` (Methods: {', '.join(c['methods'][:5])}{'...' if len(c['methods']) > 5 else ''})")
                    if "functions" in analysis and analysis["functions"]:
                        output.append(f"**Functions:** `{', '.join(analysis['functions'][:10])}`")
                    if "components" in analysis and analysis["components"]:
                        output.append(f"**React Components:** `{', '.join(analysis['components'])}`")
                output.append("")

        with open(self.map_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(output))
        
        print(f"✅ Map generated at {self.map_file}")

if __name__ == "__main__":
    mapper = ProjectMapper(".")
    mapper.generate()
